# ============================================================
# analyse.py — Quantitative Analysis Script
#
# Reads the benchmark results and calculates quantitative
# metrics for the dissertation evaluation chapter:
#
#   1. Average response latency per model per prompt type
#   2. Average response length per model per prompt type
#
# These metrics form Table 1 in the evaluation chapter,
# providing quantitative comparison between GPT-4o and
# Llama 3.3 70B across Direct and Socratic prompting.
#
# Usage:
#   python3 analyse.py
#
# Requires:
#   results/results.jsonl — generated by main.py
# ============================================================

import json
import os
from collections import defaultdict

# --- File Path ---
RESULTS_FILE = "results/results.jsonl"

# ============================================================
# LOAD RESULTS
# Reads all benchmark results from the JSONL file.
# Each line is a separate JSON record from one API call.
# ============================================================

if not os.path.exists(RESULTS_FILE):
	print("No results file found. Run main.py first.")
	exit()

results = []
with open(RESULTS_FILE, "r") as f:
	for line in f:
		line = line.strip()
		if line:  # skip empty lines
			results.append(json.loads(line))

# Show how many results were loaded and how many runs
run_numbers = set(r.get("run", 1) for r in results)
print(f"Loaded {len(results)} results across {len(run_numbers)} run(s)\n")

# ============================================================
# GROUP RESULTS
# Groups results by model and prompt type so we can
# calculate averages across all runs for each combination.
# Uses defaultdict to avoid manual key existence checks.
# ============================================================

grouped = defaultdict(list)
for r in results:
	key = (r["model"], r["prompt_type"])
	grouped[key].append(r)

# ============================================================
# CALCULATE AND DISPLAY AVERAGES
# For each model/prompt type combination, calculates:
#   - Average latency in seconds
#   - Average response length in characters
# ============================================================

print("=" * 65)
print(f"{'Model':<25} {'Prompt':<12} {'Avg Latency':>12} {'Avg Resp Len':>13}")
print("=" * 65)

for (model, prompt_type), entries in sorted(grouped.items()):
	# Calculate average latency across all runs
	avg_latency = sum(e["latency_seconds"] for e in entries) / len(entries)

	# Calculate average response length in characters
	# Used as a proxy for response verbosity
	avg_response_len = sum(len(e["response"]) for e in entries) / len(entries)

	# Shorten model name for cleaner display
	short_model = "GPT-4o" if "gpt" in model else "Llama 3.3 70B"

	print(f"{short_model:<25} {prompt_type:<12} {avg_latency:>11.3f}s {avg_response_len:>12.0f}c")

print("=" * 65)
print(f"\nNote: Latency measured in seconds (s)")
print(f"Note: Response length measured in characters (c)")
print(f"Note: Averages calculated across {len(run_numbers)} independent run(s)")