# ============================================================
# auto_score.py — Automated Qualitative Scoring Script
#
# Uses the Claude API to automatically score all benchmark
# responses using a 4-dimension educational rubric.
#
# Methodology note:
#   Automated scoring is validated against manual scores
#   on a 50% sample (via rubric.py) to assess inter-rater
#   reliability — a standard academic validity check.
#   This approach is disclosed in the methodology chapter.
#
# Scoring dimensions (0-3 each, max 12/12):
#   1. Technical Accuracy      — Is the bug correctly identified?
#   2. Explanation Clarity     — Is the explanation clear?
#   3. Novice Appropriateness  — Is it pitched for beginners?
#   4. Socratic Scaffolding    — Does it guide without revealing?
#
# Usage:
#   python3 auto_score.py
#
# Requires:
#   results/results.jsonl     — generated by main.py
#   ANTHROPIC_API_KEY         — set in .env file
#
# Output:
#   results/auto_scores.jsonl — one score record per line
# ============================================================

import os
import json
import time
from dotenv import load_dotenv
import anthropic

# --- Environment Setup ---
# Load API keys from .env file
load_dotenv()

# --- File Paths ---
RESULTS_FILE = "results/results.jsonl"
AUTO_SCORES_FILE = "results/auto_scores.jsonl"

# --- Initialise Anthropic Client ---
# Used to call Claude API for automated scoring
client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

# ============================================================
# SCORING PROMPT BUILDER
# Constructs a detailed rubric prompt for Claude to evaluate
# each LLM response. The prompt includes full rubric criteria
# and instructs Claude to return structured JSON only.
# ============================================================

def build_scoring_prompt(response_text, prompt_type, description):
	"""
	Builds the evaluation prompt sent to Claude for scoring.

	Args:
		response_text (str): The LLM response to evaluate
		prompt_type (str):   Either 'direct' or 'socratic'
		description (str):   Description of the bug being tested

	Returns:
		str: Formatted prompt string for the Claude API
	"""
	return f"""You are an expert evaluator assessing LLM responses for educational code debugging.

Score the following response across 4 dimensions. Return ONLY a JSON object with no extra text.

Context:
- Bug description: {description}
- Prompt type: {prompt_type} (direct = fix the bug, socratic = guide student with questions)

Response to evaluate:
{response_text}

Scoring rubric:

1. technical_accuracy (0-3):
   0 = incorrect or misleading
   1 = partially correct
   2 = correct but incomplete
   3 = fully correct and complete

2. explanation_clarity (0-3):
   0 = no explanation
   1 = confusing or unclear
   2 = understandable but could be clearer
   3 = clear and easy to follow

3. novice_appropriateness (0-3):
   0 = uses advanced concepts without explanation
   1 = somewhat appropriate but assumes too much knowledge
   2 = mostly appropriate for beginners
   3 = perfectly pitched for a novice programmer

4. socratic_scaffolding (0-3):
   0 = gives away the answer directly (expected for direct prompts)
   1 = minimal guidance toward solution
   2 = some guiding questions or hints
   3 = strong Socratic approach, guides without revealing answer

Return ONLY this JSON format:
{{
  "technical_accuracy": <0-3>,
  "explanation_clarity": <0-3>,
  "novice_appropriateness": <0-3>,
  "socratic_scaffolding": <0-3>,
  "reasoning": "<one sentence explaining your scores>"
}}"""


# ============================================================
# AUTO SCORE FUNCTION
# Sends a single response to Claude API and parses
# the returned JSON scores.
# ============================================================

def auto_score_response(response_text, prompt_type, description):
	"""
	Sends a response to Claude API for automated scoring.

	Args:
		response_text (str): The LLM response to evaluate
		prompt_type (str):   Either 'direct' or 'socratic'
		description (str):   Description of the bug being tested

	Returns:
		dict: Parsed scores with keys for each rubric dimension
	"""
	prompt = build_scoring_prompt(response_text, prompt_type, description)

	# Call Claude API with structured output request
	message = client.messages.create(
		model="claude-sonnet-4-20250514",
		max_tokens=300,
		messages=[{"role": "user", "content": prompt}]
	)

	# Parse the JSON response from Claude
	raw = message.content[0].text.strip()
	scores = json.loads(raw)
	return scores


# ============================================================
# LOAD BENCHMARK RESULTS
# Reads all responses from the benchmark results file.
# ============================================================

results = []
with open(RESULTS_FILE, "r") as f:
	for line in f:
		line = line.strip()
		if line:
			results.append(json.loads(line))

run_numbers = set(r.get("run", 1) for r in results)
print(f"Loaded {len(results)} results across {len(run_numbers)} run(s)")

# ============================================================
# LOAD EXISTING SCORES
# Allows the script to resume if interrupted — skips any
# responses that have already been scored.
# Uses model + test_case_id + prompt_type + run as unique key.
# ============================================================

existing = {}
if os.path.exists(AUTO_SCORES_FILE):
	with open(AUTO_SCORES_FILE, "r") as f:
		for line in f:
			line = line.strip()
			if line:
				entry = json.loads(line)
				# Include run number in key to score each run separately
				key = f"{entry['model']}_{entry['test_case_id']}_{entry['prompt_type']}_{entry.get('run', 1)}"
				existing[key] = entry

print(f"Already scored: {len(existing)}")
print(f"Remaining: {len(results) - len(existing)}\n")

# ============================================================
# MAIN SCORING LOOP
# Iterates over all benchmark results, skips already scored
# entries, and saves each score immediately to avoid data
# loss if the script is interrupted.
# ============================================================

for r in results:
	# Build unique key including run number
	key = f"{r['model']}_{r['test_case_id']}_{r['prompt_type']}_{r.get('run', 1)}"

	# Skip already scored responses
	if key in existing:
		continue

	short_model = "GPT-4o" if "gpt" in r["model"] else "Llama 3"
	print(f"Scoring {short_model} | Run {r.get('run', 1)} | {r['test_case_id']} | {r['prompt_type']}...")

	try:
		# Get automated scores from Claude API
		scores = auto_score_response(
			r["response"],
			r["prompt_type"],
			r["description"]
		)

		# Build complete score entry for storage
		entry = {
			"model": r["model"],
			"run": r.get("run", 1),
			"test_case_id": r["test_case_id"],
			"description": r["description"],
			"prompt_type": r["prompt_type"],
			"technical_accuracy": scores["technical_accuracy"],
			"explanation_clarity": scores["explanation_clarity"],
			"novice_appropriateness": scores["novice_appropriateness"],
			"socratic_scaffolding": scores["socratic_scaffolding"],
			"reasoning": scores.get("reasoning", ""),
			"total_score": sum([
				scores["technical_accuracy"],
				scores["explanation_clarity"],
				scores["novice_appropriateness"],
				scores["socratic_scaffolding"]
			]),
			"scored_by": "claude-auto"
		}

		# Save score immediately to avoid data loss
		with open(AUTO_SCORES_FILE, "a") as f:
			f.write(json.dumps(entry) + "\n")

		print(f"  Total: {entry['total_score']}/12 — {scores.get('reasoning', '')}")

		# Small delay to avoid API rate limiting
		time.sleep(0.5)

	except Exception as e:
		print(f"  ERROR scoring {r['test_case_id']}: {e}")
		continue

print(f"\nAuto scoring complete! Results saved to {AUTO_SCORES_FILE}")