# ============================================================
# generate_figures.py — Statistical Analysis & Figure Generation
#
# This script performs all statistical analysis and generates
# all figures used in Chapter 3 and Chapter 4 of the
# dissertation. It reads from the existing results and
# auto_scores data files.
#
# Statistical tests performed:
#   1. Welch's t-test (independent samples, unequal variance)
#   2. Cohen's d effect size
#   3. 95% Confidence Intervals
#   4. Mann-Whitney U (non-parametric validation)
#   5. Descriptive statistics (mean, SD, SEM, min, max)
#
# Usage:
#   python3 generate_figures.py
#
# Requires:
#   pip install matplotlib scipy numpy
#   results/results.jsonl      — generated by main.py
#   results/auto_scores.jsonl  — generated by auto_score.py
#   results/scores.jsonl       — generated by rubric.py
#
# Output:
#   figures/ — all generated PNG figures
#   statistical_report.txt — full statistical analysis report
# ============================================================

import os
import json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy import stats
from collections import defaultdict

# --- Configuration ---
plt.rcParams.update({
	'font.family': 'serif',
	'font.size': 11,
	'axes.titlesize': 13,
	'axes.labelsize': 12,
	'figure.dpi': 300,
	'savefig.dpi': 300,
	'figure.facecolor': 'white',
})

FIGURES_DIR = "figures"
os.makedirs(FIGURES_DIR, exist_ok=True)

# --- Colour Palette ---
C_GPT = '#2166AC'
C_LLAMA = '#B2182B'
C_GPT_L = '#92C5DE'
C_LLAMA_L = '#F4A582'

# ============================================================
# LOAD DATA
# ============================================================

with open('results/results.jsonl') as f:
	results = [json.loads(l) for l in f if l.strip()]

with open('results/auto_scores.jsonl') as f:
	scores = [json.loads(l) for l in f if l.strip()]

manual_scores = []
if os.path.exists('results/scores.jsonl'):
	with open('results/scores.jsonl') as f:
		manual_scores = [json.loads(l) for l in f if l.strip()]

print(f"Loaded {len(results)} results and {len(scores)} auto scores")
print(f"Loaded {len(manual_scores)} manual scores")

# --- Helper ---
def model_label(m):
	return "GPT-4o" if "gpt" in m else "Llama 3.3 70B"

def cohens_d(a, b):
	return (np.mean(a) - np.mean(b)) / np.sqrt(
		(np.std(a, ddof=1)**2 + np.std(b, ddof=1)**2) / 2
	)

dims = ['technical_accuracy', 'explanation_clarity',
		'novice_appropriateness', 'socratic_scaffolding']
dim_labels = ['Technical\nAccuracy', 'Explanation\nClarity',
			  'Novice\nAppropriateness', 'Socratic\nScaffolding']

# ============================================================
# STATISTICAL ANALYSIS
# ============================================================

print("\n" + "=" * 60)
print("STATISTICAL ANALYSIS")
print("=" * 60)

gpt_d = [s['total_score'] for s in scores
		 if 'gpt' in s['model'] and s['prompt_type'] == 'direct']
llama_d = [s['total_score'] for s in scores
		   if 'llama' in s['model'] and s['prompt_type'] == 'direct']
gpt_s = [s['total_score'] for s in scores
		 if 'gpt' in s['model'] and s['prompt_type'] == 'socratic']
llama_s = [s['total_score'] for s in scores
		   if 'llama' in s['model'] and s['prompt_type'] == 'socratic']

# --- Welch's t-tests ---
t1, p1 = stats.ttest_ind(gpt_d, llama_d, equal_var=False)
t2, p2 = stats.ttest_ind(gpt_s, llama_s, equal_var=False)
t3, p3 = stats.ttest_ind(gpt_d, gpt_s, equal_var=False)
t4, p4 = stats.ttest_ind(llama_d, llama_s, equal_var=False)

# --- Cohen's d ---
cd1 = cohens_d(gpt_d, llama_d)
cd2 = cohens_d(gpt_s, llama_s)
cd3 = cohens_d(gpt_s, gpt_d)
cd4 = cohens_d(llama_s, llama_d)

# --- Mann-Whitney U ---
u1, up1 = stats.mannwhitneyu(gpt_d, llama_d, alternative='two-sided')
u2, up2 = stats.mannwhitneyu(gpt_s, llama_s, alternative='two-sided')

# --- Print Report ---
report = []
report.append("1. DESCRIPTIVE STATISTICS")
report.append("-" * 60)
for model in ['gpt-4o', 'llama-3.3-70b-versatile']:
	for pt in ['direct', 'socratic']:
		vals = [s['total_score'] for s in scores
				if s['model'] == model and s['prompt_type'] == pt]
		label = f"{model_label(model)} {pt.title()}"
		report.append(f"  {label:<28} N={len(vals):>3}  "
					  f"Mean={np.mean(vals):.3f}  "
					  f"SD={np.std(vals, ddof=1):.3f}  "
					  f"SEM={stats.sem(vals):.3f}  "
					  f"Min={min(vals)}  Max={max(vals)}")

report.append(f"\n2. WELCH'S T-TESTS")
report.append("-" * 60)
report.append(f"  GPT vs Llama (Direct):    t={t1:.3f}, p={p1:.4f}, d={cd1:.3f}")
report.append(f"  GPT vs Llama (Socratic):  t={t2:.3f}, p={p2:.4f}, d={cd2:.3f}")
report.append(f"  GPT Direct vs Socratic:   t={t3:.3f}, p={p3:.6f}, d={cd3:.3f}")
report.append(f"  Llama Direct vs Socratic:  t={t4:.3f}, p={p4:.6f}, d={cd4:.3f}")

report.append(f"\n3. MANN-WHITNEY U TESTS")
report.append("-" * 60)
report.append(f"  Direct (GPT vs Llama):    U={u1:.1f}, p={up1:.4f}")
report.append(f"  Socratic (GPT vs Llama):  U={u2:.1f}, p={up2:.4f}")

report_text = "\n".join(report)
print(report_text)

with open("statistical_report.txt", "w") as f:
	f.write(report_text)

# ============================================================
# FIGURE GENERATION
# ============================================================

# --- Fig: Composite Scores ---
print("\nGenerating figures...")

fig, ax = plt.subplots(figsize=(8, 5))
gpt_means = [np.mean(gpt_d), np.mean(gpt_s)]
llama_means = [np.mean(llama_d), np.mean(llama_s)]
gpt_sems = [stats.sem(gpt_d), stats.sem(gpt_s)]
llama_sems = [stats.sem(llama_d), stats.sem(llama_s)]
x = np.arange(2); w = 0.30
b1 = ax.bar(x-w/2, gpt_means, w, yerr=gpt_sems, label='GPT-4o',
			color=C_GPT, edgecolor='black', linewidth=0.5, capsize=4, zorder=3)
b2 = ax.bar(x+w/2, llama_means, w, yerr=llama_sems, label='Llama 3.3 70B',
			color=C_LLAMA, edgecolor='black', linewidth=0.5, capsize=4, zorder=3)
for bar, m in zip(b1, gpt_means):
	ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2,
			f'{m:.2f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
for bar, m in zip(b2, llama_means):
	ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2,
			f'{m:.2f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
ax.set_ylabel('Mean Composite Score (out of 12)')
ax.set_xticks(x); ax.set_xticklabels(['Direct', 'Socratic'])
ax.set_ylim(0, 13.5); ax.legend(loc='upper left')
ax.grid(axis='y', alpha=0.3, zorder=0)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/composite_scores.png", bbox_inches='tight')
plt.close()

# --- Fig: Dimension Breakdown ---
fig, axes = plt.subplots(1, 2, figsize=(14, 5.5), sharey=True)
for idx, (pt, title) in enumerate([('direct','Direct Prompting'),
									 ('socratic','Socratic Prompting')]):
	ax = axes[idx]
	gm, lm, gs, ls = [], [], [], []
	for dim in dims:
		gv = [s[dim] for s in scores if 'gpt' in s['model'] and s['prompt_type']==pt]
		lv = [s[dim] for s in scores if 'llama' in s['model'] and s['prompt_type']==pt]
		gm.append(np.mean(gv)); lm.append(np.mean(lv))
		gs.append(stats.sem(gv)); ls.append(stats.sem(lv))
	x = np.arange(len(dims)); w = 0.30
	ax.bar(x-w/2, gm, w, yerr=gs, label='GPT-4o', color=C_GPT,
		   edgecolor='black', linewidth=0.5, capsize=3, zorder=3)
	ax.bar(x+w/2, lm, w, yerr=ls, label='Llama 3.3 70B', color=C_LLAMA,
		   edgecolor='black', linewidth=0.5, capsize=3, zorder=3)
	ax.set_title(title, fontweight='bold')
	ax.set_xticks(x); ax.set_xticklabels(dim_labels, fontsize=9)
	ax.set_ylim(0, 3.8); ax.axhline(y=3, color='grey', linestyle='--', alpha=0.3)
	ax.grid(axis='y', alpha=0.3, zorder=0)
	if idx == 0: ax.set_ylabel('Mean Score (out of 3)')
	ax.legend(loc='lower right', fontsize=9)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/dimension_breakdown.png", bbox_inches='tight')
plt.close()

# --- Fig: Stacked Dimensions ---
fig, ax = plt.subplots(figsize=(9, 5))
conds = [('gpt-4o','direct','GPT-4o\nDirect'),
		 ('gpt-4o','socratic','GPT-4o\nSocratic'),
		 ('llama-3.3-70b-versatile','direct','Llama 3.3\nDirect'),
		 ('llama-3.3-70b-versatile','socratic','Llama 3.3\nSocratic')]
dim_colors = ['#2166AC','#4393C3','#92C5DE','#D1E5F0']
dim_short = ['Technical Accuracy','Explanation Clarity',
			 'Novice Appropriateness','Socratic Scaffolding']
x = np.arange(len(conds)); bottoms = np.zeros(len(conds))
for d_idx, dim in enumerate(dims):
	values = [np.mean([s[dim] for s in scores
			  if s['model']==m and s['prompt_type']==p]) for m,p,_ in conds]
	ax.bar(x, values, bottom=bottoms, color=dim_colors[d_idx], edgecolor='black',
		   linewidth=0.5, label=dim_short[d_idx], width=0.55, zorder=3)
	for i, v in enumerate(values):
		if v > 0.3:
			ax.text(i, bottoms[i]+v/2, f'{v:.2f}', ha='center', va='center',
					fontsize=8, fontweight='bold')
	bottoms += values
for i, total in enumerate(bottoms):
	ax.text(i, total+0.15, f'{total:.2f}', ha='center', va='bottom',
			fontsize=10, fontweight='bold')
ax.set_xticks(x); ax.set_xticklabels([c[2] for c in conds])
ax.set_ylabel('Mean Score'); ax.set_ylim(0, 14)
ax.legend(loc='upper left', fontsize=8); ax.grid(axis='y', alpha=0.3, zorder=0)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/stacked_dimensions.png", bbox_inches='tight')
plt.close()

# --- Fig: Radar Chart ---
fig, axes = plt.subplots(1, 2, figsize=(12, 5), subplot_kw=dict(polar=True))
for ax_idx, (pt, title) in enumerate([('direct','Direct Prompting'),
										('socratic','Socratic Prompting')]):
	ax = axes[ax_idx]
	angles = np.linspace(0, 2*np.pi, len(dims), endpoint=False).tolist()
	angles += angles[:1]
	for model, color, label in [('gpt-4o',C_GPT,'GPT-4o'),
								 ('llama-3.3-70b-versatile',C_LLAMA,'Llama 3.3 70B')]:
		values = [np.mean([s[d] for s in scores
				  if s['model']==model and s['prompt_type']==pt]) for d in dims]
		values += values[:1]
		ax.plot(angles, values, color=color, linewidth=2, label=label, marker='o', markersize=5)
		ax.fill(angles, values, color=color, alpha=0.1)
	ax.set_xticks(angles[:-1]); ax.set_xticklabels(dim_labels, fontsize=8)
	ax.set_ylim(0, 3.2); ax.set_yticks([1,2,3])
	ax.set_title(title, fontweight='bold', pad=20)
	ax.legend(loc='lower right', fontsize=8, bbox_to_anchor=(1.15,-0.1))
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/radar_dimensions.png", bbox_inches='tight')
plt.close()

# --- Fig: Latency Comparison ---
fig, ax = plt.subplots(figsize=(8, 5))
gpt_lm, llama_lm, gpt_ls, llama_ls = [], [], [], []
for pt in ['direct','socratic']:
	gl = [r['latency_seconds'] for r in results if 'gpt' in r['model'] and r['prompt_type']==pt]
	ll = [r['latency_seconds'] for r in results if 'llama' in r['model'] and r['prompt_type']==pt]
	gpt_lm.append(np.mean(gl)); llama_lm.append(np.mean(ll))
	gpt_ls.append(stats.sem(gl)); llama_ls.append(stats.sem(ll))
x = np.arange(2); w = 0.30
b1 = ax.bar(x-w/2, gpt_lm, w, yerr=gpt_ls, label='GPT-4o',
			color=C_GPT, edgecolor='black', linewidth=0.5, capsize=4, zorder=3)
b2 = ax.bar(x+w/2, llama_lm, w, yerr=llama_ls, label='Llama 3.3 70B',
			color=C_LLAMA, edgecolor='black', linewidth=0.5, capsize=4, zorder=3)
for bar, m in zip(b1, gpt_lm):
	ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.1,
			f'{m:.2f}s', ha='center', va='bottom', fontsize=10, fontweight='bold')
for bar, m in zip(b2, llama_lm):
	ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.1,
			f'{m:.2f}s', ha='center', va='bottom', fontsize=10, fontweight='bold')
ax.set_ylabel('Mean Response Latency (seconds)')
ax.set_xticks(x); ax.set_xticklabels(['Direct','Socratic'])
ax.legend(loc='upper right'); ax.grid(axis='y', alpha=0.3, zorder=0)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/latency_comparison.png", bbox_inches='tight')
plt.close()

# --- Fig: Latency Box Plot ---
fig, ax = plt.subplots(figsize=(8, 5))
box_data, box_labels, box_colors = [], [], []
for model, label, c in [('gpt-4o','GPT-4o',C_GPT),
						  ('llama-3.3-70b-versatile','Llama 3.3 70B',C_LLAMA)]:
	for pt in ['direct','socratic']:
		lat = [r['latency_seconds'] for r in results
			   if r['model']==model and r['prompt_type']==pt]
		box_data.append(lat)
		box_labels.append(f'{label}\n{pt.title()}')
		box_colors.append(c)
bp = ax.boxplot(box_data, tick_labels=box_labels, patch_artist=True, widths=0.5,
				medianprops=dict(color='black', linewidth=2))
for patch, color in zip(bp['boxes'], box_colors):
	patch.set_facecolor(color); patch.set_alpha(0.7)
ax.set_ylabel('Response Latency (seconds)')
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/latency_boxplot.png", bbox_inches='tight')
plt.close()

# --- Fig: Response Length ---
fig, ax = plt.subplots(figsize=(8, 5))
box_data = []
for model, label, c in [('gpt-4o','GPT-4o',C_GPT),
						  ('llama-3.3-70b-versatile','Llama 3.3 70B',C_LLAMA)]:
	for pt in ['direct','socratic']:
		lengths = [len(r['response']) for r in results
				   if r['model']==model and r['prompt_type']==pt]
		box_data.append(lengths)
bl = ['GPT-4o\nDirect','GPT-4o\nSocratic','Llama 3.3\nDirect','Llama 3.3\nSocratic']
bc = [C_GPT, C_GPT, C_LLAMA, C_LLAMA]
bp = ax.boxplot(box_data, tick_labels=bl, patch_artist=True, widths=0.5,
				medianprops=dict(color='black', linewidth=2))
for patch, color in zip(bp['boxes'], bc):
	patch.set_facecolor(color); patch.set_alpha(0.7)
ax.set_ylabel('Response Length (characters)')
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/response_length.png", bbox_inches='tight')
plt.close()

# --- Fig: Latency vs Score ---
fig, ax = plt.subplots(figsize=(8, 5))
for model, color, marker, label in [('gpt-4o',C_GPT,'o','GPT-4o'),
									  ('llama-3.3-70b-versatile',C_LLAMA,'s','Llama 3.3 70B')]:
	for pt, alpha in [('direct',0.4),('socratic',0.9)]:
		lats, scrs = [], []
		for r in results:
			if r['model']==model and r['prompt_type']==pt:
				matching = [s for s in scores if s['model']==model and s['prompt_type']==pt
						   and s['test_case_id']==r['test_case_id'] and s['run']==r['run']]
				if matching:
					lats.append(r['latency_seconds'])
					scrs.append(matching[0]['total_score'])
		ax.scatter(lats, scrs, c=color, marker=marker, alpha=alpha, s=40,
				  label=f'{label} ({pt.title()})', edgecolors='black', linewidth=0.3)
ax.set_xlabel('Response Latency (seconds)')
ax.set_ylabel('Composite Score (out of 12)')
ax.legend(fontsize=8, loc='lower right'); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/latency_vs_score.png", bbox_inches='tight')
plt.close()

# --- Fig: Heatmap ---
test_case_ids = sorted(set(s['test_case_id'] for s in scores))
conds_hm = [('gpt-4o','direct','GPT-4o\nDirect'),
			 ('gpt-4o','socratic','GPT-4o\nSocratic'),
			 ('llama-3.3-70b-versatile','direct','Llama 3.3\nDirect'),
			 ('llama-3.3-70b-versatile','socratic','Llama 3.3\nSocratic')]
hm = np.zeros((len(conds_hm), len(test_case_ids)))
for i,(model,pt,_) in enumerate(conds_hm):
	for j,tc in enumerate(test_case_ids):
		vals = [s['total_score'] for s in scores
				if s['model']==model and s['prompt_type']==pt and s['test_case_id']==tc]
		hm[i,j] = np.mean(vals) if vals else 0
fig, ax = plt.subplots(figsize=(16, 4))
im = ax.imshow(hm, cmap='RdYlGn', aspect='auto', vmin=0, vmax=12)
ax.set_xticks(np.arange(len(test_case_ids)))
ax.set_xticklabels(test_case_ids, fontsize=8, rotation=45, ha='right')
ax.set_yticks(np.arange(len(conds_hm)))
ax.set_yticklabels([c[2] for c in conds_hm], fontsize=9)
for i in range(len(conds_hm)):
	for j in range(len(test_case_ids)):
		val = hm[i,j]
		color = 'white' if val < 5 or val > 10 else 'black'
		ax.text(j, i, f'{val:.1f}', ha='center', va='center',
				fontsize=7, color=color, fontweight='bold')
plt.colorbar(im, ax=ax, shrink=0.8).set_label('Mean Score (out of 12)')
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/testcase_heatmap.png", bbox_inches='tight')
plt.close()

# --- Fig: Category Performance ---
categories = {
	'TC001':'Division/Zero','TC002':'Index/Range','TC003':'Mutable Default',
	'TC004':'Logic/Indent','TC005':'Type Error','TC006':'Variable Scope',
	'TC007':'Infinite Loop','TC008':'Missing Return','TC009':'List Mutation',
	'TC010':'Boolean Logic','TC011':'Division/Zero','TC012':'Index/Range',
	'TC013':'Variable Scope','TC014':'Infinite Loop','TC015':'Logic/Indent',
	'TC016':'List Method','TC017':'Type Error','TC018':'Assign vs Equal',
	'TC019':'Dict Key','TC020':'Var Shadowing'
}
cat_scores = defaultdict(list)
for s in scores:
	cat_scores[categories.get(s['test_case_id'],'Other')].append(s['total_score'])
sorted_cats = sorted(cat_scores.items(), key=lambda x: np.mean(x[1]))
fig, ax = plt.subplots(figsize=(10, 5))
colors_cat = ['#D73027' if np.mean(v)<9 else '#FC8D59' if np.mean(v)<10
			  else '#91BFDB' if np.mean(v)<11 else '#4575B4' for _,v in sorted_cats]
bars = ax.barh(range(len(sorted_cats)), [np.mean(v) for _,v in sorted_cats],
			   xerr=[stats.sem(v) for _,v in sorted_cats], color=colors_cat,
			   edgecolor='black', linewidth=0.5, capsize=3, height=0.6, zorder=3)
ax.set_yticks(range(len(sorted_cats)))
ax.set_yticklabels([c[0] for c in sorted_cats], fontsize=9)
ax.set_xlabel('Mean Composite Score (out of 12)')
ax.set_xlim(0, 13); ax.grid(axis='x', alpha=0.3, zorder=0)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/category_performance.png", bbox_inches='tight')
plt.close()

# --- Fig: Problem Test Cases ---
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax_idx, (tc_id, tc_title) in enumerate([('TC010','TC010: Boolean Logic'),
											  ('TC004','TC004: Indentation')]):
	ax = axes[ax_idx]
	conds_tc = [('gpt-4o','direct','GPT-4o\nDirect'),
				('gpt-4o','socratic','GPT-4o\nSocratic'),
				('llama-3.3-70b-versatile','direct','Llama\nDirect'),
				('llama-3.3-70b-versatile','socratic','Llama\nSocratic')]
	means = [np.mean([s['total_score'] for s in scores
			 if s['model']==m and s['prompt_type']==p and s['test_case_id']==tc_id])
			 for m,p,_ in conds_tc]
	colors_tc = [C_GPT_L, C_GPT, C_LLAMA_L, C_LLAMA]
	xp = np.arange(len(conds_tc))
	bars = ax.bar(xp, means, color=colors_tc, edgecolor='black', linewidth=0.5, width=0.6, zorder=3)
	for bar, m in zip(bars, means):
		ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.3,
				f'{m:.1f}', ha='center', va='bottom', fontsize=10, fontweight='bold')
	ax.set_xticks(xp); ax.set_xticklabels([c[2] for c in conds_tc], fontsize=9)
	ax.set_ylim(0, 14); ax.set_ylabel('Mean Score (out of 12)')
	ax.set_title(tc_title, fontweight='bold', fontsize=11)
	ax.grid(axis='y', alpha=0.3, zorder=0)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/problem_testcases.png", bbox_inches='tight')
plt.close()

# --- Fig: Score Distribution ---
fig, axes = plt.subplots(1, 2, figsize=(12, 5), sharey=True)
for idx, (pt, title) in enumerate([('direct','Direct'),('socratic','Socratic')]):
	ax = axes[idx]
	gv = [s['total_score'] for s in scores if 'gpt' in s['model'] and s['prompt_type']==pt]
	lv = [s['total_score'] for s in scores if 'llama' in s['model'] and s['prompt_type']==pt]
	bins = np.arange(0, 14) - 0.5
	ax.hist(gv, bins=bins, alpha=0.6, color=C_GPT, label='GPT-4o', edgecolor='black', linewidth=0.5)
	ax.hist(lv, bins=bins, alpha=0.6, color=C_LLAMA, label='Llama 3.3 70B', edgecolor='black', linewidth=0.5)
	ax.set_title(title, fontweight='bold')
	ax.set_xlabel('Composite Score (out of 12)')
	if idx == 0: ax.set_ylabel('Frequency')
	ax.legend(fontsize=9); ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/score_distribution.png", bbox_inches='tight')
plt.close()

# --- Fig: Socratic Improvement ---
fig, ax = plt.subplots(figsize=(7, 5))
direct_m = [np.mean(gpt_d), np.mean(llama_d)]
socratic_m = [np.mean(gpt_s), np.mean(llama_s)]
x = np.arange(2); w = 0.30
ax.bar(x-w/2, direct_m, w, label='Direct', color=[C_GPT_L,C_LLAMA_L],
	   edgecolor='black', linewidth=0.5, zorder=3)
ax.bar(x+w/2, socratic_m, w, label='Socratic', color=[C_GPT,C_LLAMA],
	   edgecolor='black', linewidth=0.5, zorder=3)
for i, (d, s) in enumerate(zip(direct_m, socratic_m)):
	pct = ((s-d)/d)*100
	ax.annotate(f'+{pct:.1f}%', xy=(i, max(d,s)+0.4), ha='center',
				fontsize=11, fontweight='bold', color='green')
ax.set_ylabel('Mean Composite Score (out of 12)')
ax.set_xticks(x); ax.set_xticklabels(['GPT-4o','Llama 3.3 70B'])
ax.set_ylim(0, 14); ax.legend(loc='upper left')
ax.grid(axis='y', alpha=0.3, zorder=0)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/socratic_improvement.png", bbox_inches='tight')
plt.close()

# --- Fig: Effect Sizes ---
fig, ax = plt.subplots(figsize=(9, 4.5))
effects = [
	("GPT-4o vs Llama 3.3 70B\n(Direct)", cd1),
	("GPT-4o vs Llama 3.3 70B\n(Socratic)", cd2),
	("GPT-4o\nDirect → Socratic", cd3),
	("Llama 3.3 70B\nDirect → Socratic", cd4),
]
bar_colors = ['#888888','#4393C3',C_GPT,C_LLAMA]
bars = ax.barh(range(len(effects)), [e[1] for e in effects],
			   color=bar_colors, edgecolor='black', linewidth=0.5, height=0.5)
for bar, val in zip(bars, [e[1] for e in effects]):
	x_pos = val+0.08 if val >= 0 else val-0.08
	ha = 'left' if val >= 0 else 'right'
	ax.text(x_pos, bar.get_y()+bar.get_height()/2, f'd = {val:.3f}',
			va='center', ha=ha, fontweight='bold', fontsize=10)
ax.axvspan(0,0.2,alpha=0.05,color='green',label='Negligible')
ax.axvspan(0.2,0.5,alpha=0.08,color='yellow',label='Small')
ax.axvspan(0.5,0.8,alpha=0.08,color='orange',label='Medium')
ax.axvspan(0.8,3.5,alpha=0.08,color='red',label='Large')
ax.axvline(x=0, color='black', linewidth=0.5)
ax.set_yticks(range(len(effects)))
ax.set_yticklabels([e[0] for e in effects], fontsize=9)
ax.set_xlabel("Cohen's d Effect Size")
ax.legend(loc='center right', fontsize=7, title='Thresholds')
ax.set_xlim(-0.5, 3.5); ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/effect_sizes.png", bbox_inches='tight')
plt.close()

# --- Fig: Run Consistency ---
fig, ax = plt.subplots(figsize=(8, 5))
runs_list = sorted(set(s['run'] for s in scores))
for model, color, label in [('gpt-4o',C_GPT,'GPT-4o'),
							  ('llama-3.3-70b-versatile',C_LLAMA,'Llama 3.3 70B')]:
	for pt, ls in [('direct','--'),('socratic','-')]:
		rm = [np.mean([s['total_score'] for s in scores
			  if s['model']==model and s['prompt_type']==pt and s['run']==run])
			  for run in runs_list]
		ax.plot(runs_list, rm, color=color, linestyle=ls, marker='o', markersize=6,
				label=f'{label} ({pt.title()})', linewidth=2)
ax.set_xlabel('Run Number'); ax.set_ylabel('Mean Composite Score (out of 12)')
ax.set_xticks(runs_list); ax.set_ylim(6, 13)
ax.legend(loc='center right', fontsize=9); ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig(f"{FIGURES_DIR}/run_consistency.png", bbox_inches='tight')
plt.close()

# --- Fig: Inter-rater Reliability ---
if manual_scores:
	fig, ax = plt.subplots(figsize=(8, 5))
	manual_t, auto_t, labels_irr = [], [], []
	for ms in manual_scores:
		manual_t.append(ms['total_score'])
		matching = [s for s in scores if s['model']==ms['model']
					and s['test_case_id']==ms['test_case_id']
					and s['prompt_type']==ms['prompt_type'] and s.get('run',1)==1]
		auto_t.append(matching[0]['total_score'] if matching else 0)
		short = "GPT" if "gpt" in ms['model'] else "Llama"
		labels_irr.append(f"{short}\n{ms['test_case_id']}\n{ms['prompt_type'][:3]}")
	x = np.arange(len(manual_t)); w = 0.30
	ax.bar(x-w/2, manual_t, w, label='Manual (Researcher)', color='#2CA02C',
		   edgecolor='black', linewidth=0.5, zorder=3)
	ax.bar(x+w/2, auto_t, w, label='Automated (Claude API)', color='#9467BD',
		   edgecolor='black', linewidth=0.5, zorder=3)
	for i, (m, a) in enumerate(zip(manual_t, auto_t)):
		ax.text(i-w/2, m+0.2, str(m), ha='center', fontsize=9, fontweight='bold')
		ax.text(i+w/2, a+0.2, str(a), ha='center', fontsize=9, fontweight='bold')
	ax.set_xticks(x); ax.set_xticklabels(labels_irr, fontsize=8)
	ax.set_ylabel('Total Score (out of 12)'); ax.set_ylim(0, 14)
	ax.legend(loc='upper right', fontsize=9); ax.grid(axis='y', alpha=0.3, zorder=0)
	diffs = [abs(m-a) for m, a in zip(manual_t, auto_t)]
	ax.text(0.02, 0.97, f'Mean absolute difference: {np.mean(diffs):.2f}',
			transform=ax.transAxes, fontsize=10, fontweight='bold', va='top',
			bbox=dict(boxstyle='round,pad=0.3', facecolor='lightyellow', edgecolor='black'))
	plt.tight_layout()
	plt.savefig(f"{FIGURES_DIR}/interrater_reliability.png", bbox_inches='tight')
	plt.close()

# --- Formula Figures ---
for name, formula, desc in [
	('formula_sem', r"$SEM = \frac{s}{\sqrt{n}}$",
	 r"where $s$ = sample standard deviation, $n$ = sample size"),
	('formula_welch_ttest',
	 r"$t = \frac{\bar{X}_1 - \bar{X}_2}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}$",
	 r"where $\bar{X}$ = sample mean, $s^2$ = sample variance, $n$ = sample size"),
	('formula_cohens_d',
	 r"$d = \frac{\bar{X}_1 - \bar{X}_2}{\sqrt{\frac{s_1^2 + s_2^2}{2}}}$",
	 r"Thresholds: $|d| < 0.2$ negligible, $0.2$–$0.5$ small, $> 0.8$ large"),
	('formula_ci',
	 r"$CI_{95\%} = \bar{X} \pm 1.96 \times \frac{s}{\sqrt{n}}$",
	 r"where $\bar{X}$ = sample mean, $s$ = standard deviation, $n$ = sample size"),
	('formula_mann_whitney',
	 r"$U = n_1 n_2 + \frac{n_1(n_1+1)}{2} - R_1$",
	 r"where $n_1, n_2$ = sample sizes, $R_1$ = sum of ranks for sample 1"),
]:
	fig, ax = plt.subplots(figsize=(7, 2.5))
	ax.axis('off')
	ax.text(0.5, 0.55, formula, fontsize=28, ha='center', va='center',
			transform=ax.transAxes)
	ax.text(0.5, 0.08, desc, fontsize=11, ha='center', va='center',
			transform=ax.transAxes, style='italic', color='#444444')
	plt.tight_layout()
	plt.savefig(f"{FIGURES_DIR}/{name}.png", bbox_inches='tight')
	plt.close()

print(f"\n✓ All figures saved to {FIGURES_DIR}/")
print(f"✓ Statistical report saved to statistical_report.txt")