# ============================================================
# rubric.py - Interactive Manual Scoring Tool
#
# Provides an interactive command-line interface for manually
# scoring LLM responses across 4 educational quality dimensions.
#
# This tool serves two purposes:
#   1. Primary scoring method (if used alone)
#   2. Validation tool for inter-rater reliability checking
#      against automated scores from auto_score.py
#
# Scoring Dimensions (0-3 each, max 12/12):
#   1. Technical Accuracy     - Is the bug correctly identified?
#   2. Explanation Clarity    - Is the explanation clear?
#   3. Novice Appropriateness - Is it pitched for beginners?
#   4. Socratic Scaffolding   - Does it guide without revealing?
#
# Usage:
#   python3 rubric.py
#
#   Enter 0-3 for each dimension when prompted.
#   Enter 's' to skip a response and continue later.
#   Progress is saved after each response - safe to quit
#   and resume at any time.
#
# Requires:
#   results/results.jsonl - generated by main.py
#
# Output:
#   results/scores.jsonl - one score record per line
# ============================================================

import json
import os

# --- File Paths ---
RESULTS_FILE = "results/results.jsonl"
SCORES_FILE = "results/scores.jsonl"

# --- Rubric Dimensions ---
# Defines the 4 scoring dimensions used in evaluation
DIMENSIONS = [
	"technical_accuracy",
	"explanation_clarity",
	"novice_appropriateness",
	"socratic_scaffolding"
]

# ============================================================
# LOAD BENCHMARK RESULTS
# Reads all LLM responses to be scored.
# ============================================================

results = []
with open(RESULTS_FILE, "r") as f:
	for line in f:
		line = line.strip()
		if line:
			results.append(json.loads(line))

# ============================================================
# LOAD EXISTING SCORES
# Allows scoring to resume if interrupted.
# Uses model + test_case_id + prompt_type + run as unique key
# so each run's responses can be scored independently.
# ============================================================

existing_scores = {}
if os.path.exists(SCORES_FILE):
	with open(SCORES_FILE, "r") as f:
		for line in f:
			line = line.strip()
			if line:
				score = json.loads(line)
				key = f"{score['model']}_{score['test_case_id']}_{score['prompt_type']}_{score.get('run', 1)}"
				existing_scores[key] = score

# Display session summary
print(f"Loaded {len(results)} results")
print(f"Already scored: {len(existing_scores)}")
print(f"Remaining: {len(results) - len(existing_scores)}")
print("\nScoring instructions:")
print("  Enter 0, 1, 2, or 3 for each dimension")
print("  Enter 's' to skip a response and continue later")
print("  Progress is saved after each response\n")

# ============================================================
# SCORING LOOP
# Displays each response and collects scores from the user.
# Skips already scored responses automatically.
# Saves each score immediately after entry.
# ============================================================

for r in results:
	key = f"{r['model']}_{r['test_case_id']}_{r['prompt_type']}_{r.get('run', 1)}"

	# Skip already scored responses
	if key in existing_scores:
		continue

	# --- Display Response ---
	short_model = "GPT-4o" if "gpt" in r["model"] else "Llama 3"
	print("\n" + "=" * 60)
	print(f"Model: {short_model} | Run: {r.get('run', 1)} | Test: {r['test_case_id']} | Type: {r['prompt_type']}")
	print(f"Description: {r['description']}")
	print("-" * 60)
	print(f"RESPONSE:\n{r['response']}")
	print("-" * 60)

	# --- Collect Scores ---
	scores = {}
	skip = False

	for dim in DIMENSIONS:
		while True:
			val = input(f"Score {dim} (0-3) or 's' to skip: ").strip()
			if val == "s":
				skip = True
				break
			if val in ["0", "1", "2", "3"]:
				scores[dim] = int(val)
				break
			print("  Please enter 0, 1, 2, or 3")

		if skip:
			break

	if skip:
		continue

	# --- Calculate and Save Score ---
	total = sum(scores.values())

	score_entry = {
		"model": r["model"],
		"run": r.get("run", 1),
		"test_case_id": r["test_case_id"],
		"description": r["description"],
		"prompt_type": r["prompt_type"],
		**scores,
		"total_score": total,
		"scored_by": "manual"
	}

	# Save immediately to avoid data loss
	with open(SCORES_FILE, "a") as f:
		f.write(json.dumps(score_entry) + "\n")

	print(f"  Saved! Total score: {total}/12")

print("\nScoring session complete!")
print(f"Scores saved to {SCORES_FILE}")