# ============================================================
# summary.py — Qualitative Score Summary
#
# Reads the automated scoring results and produces a summary
# table of average qualitative scores for the dissertation
# evaluation chapter.
#
# Shows average scores per model per prompt type, averaged
# across all runs and test cases. Also shows a per-run
# breakdown to demonstrate consistency across trials.
#
# Usage:
#   python3 summary.py
#
# Requires:
#   results/auto_scores.jsonl — generated by auto_score.py
# ============================================================

import json
from collections import defaultdict

# --- File Path ---
AUTO_SCORES_FILE = "results/auto_scores.jsonl"

# ============================================================
# LOAD AUTO SCORES
# Reads all scored results from the JSONL file.
# ============================================================

scores = []
with open(AUTO_SCORES_FILE, "r") as f:
	for line in f:
		if line.strip():
			scores.append(json.loads(line))

run_numbers = set(s.get("run", 1) for s in scores)
print(f"Loaded {len(scores)} scores across {len(run_numbers)} run(s)\n")

# ============================================================
# OVERALL SUMMARY TABLE
# Groups results by model and prompt type, averages total
# scores across all runs and test cases.
# ============================================================

# Group scores by model and prompt type
grouped = defaultdict(list)
for s in scores:
	key = (s["model"], s["prompt_type"])
	grouped[key].append(s["total_score"])

# Display overall summary table
print("=" * 55)
print("OVERALL AVERAGE SCORES (all runs combined)")
print("=" * 55)
print(f"{'Model':<25} {'Prompt':<12} {'Avg Score':>10}")
print("-" * 55)

for (model, prompt_type), totals in sorted(grouped.items()):
	avg = sum(totals) / len(totals)
	short = "GPT-4o" if "gpt" in model else "Llama 3.3 70B"
	print(f"{short:<25} {prompt_type:<12} {avg:>7.2f}/12")

print("=" * 55)

# ============================================================
# PER-RUN BREAKDOWN TABLE
# Shows scores for each individual run to demonstrate
# consistency and reliability across trials.
# This supports the replication methodology argument.
# ============================================================

print("\n")
print("=" * 55)
print("PER-RUN BREAKDOWN (consistency check)")
print("=" * 55)

for run in sorted(run_numbers):
	print(f"\n--- Run {run} ---")
    
	# Filter scores for this run only
	run_scores = [s for s in scores if s.get("run", 1) == run]
    
	# Group by model and prompt type
	run_grouped = defaultdict(list)
	for s in run_scores:
		key = (s["model"], s["prompt_type"])
		run_grouped[key].append(s["total_score"])
    
	for (model, prompt_type), totals in sorted(run_grouped.items()):
		avg = sum(totals) / len(totals)
		short = "GPT-4o" if "gpt" in model else "Llama 3.3 70B"
		print(f"  {short:<23} {prompt_type:<12} {avg:>7.2f}/12")

print("\n" + "=" * 55)
print("Note: Scores out of 12 (4 dimensions x 3 max each)")
print("Note: Higher scores = better educational response quality")